package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/petri-board-arena/graph/model"
)

// CreateArena is the resolver for the createArena field.
func (r *mutationResolver) CreateArena(ctx context.Context, input model.CreateArenaInput) (*model.CreateArenaPayload, error) {
	panic(fmt.Errorf("not implemented: CreateArena - createArena"))
}

// StartArena is the resolver for the startArena field.
func (r *mutationResolver) StartArena(ctx context.Context, input model.StartArenaInput) (*model.StartArenaPayload, error) {
	panic(fmt.Errorf("not implemented: StartArena - startArena"))
}

// PauseArena is the resolver for the pauseArena field.
func (r *mutationResolver) PauseArena(ctx context.Context, input model.PauseArenaInput) (*model.PauseArenaPayload, error) {
	panic(fmt.Errorf("not implemented: PauseArena - pauseArena"))
}

// ResumeArena is the resolver for the resumeArena field.
func (r *mutationResolver) ResumeArena(ctx context.Context, input model.ResumeArenaInput) (*model.ResumeArenaPayload, error) {
	panic(fmt.Errorf("not implemented: ResumeArena - resumeArena"))
}

// StopArena is the resolver for the stopArena field.
func (r *mutationResolver) StopArena(ctx context.Context, input model.StopArenaInput) (*model.StopArenaPayload, error) {
	panic(fmt.Errorf("not implemented: StopArena - stopArena"))
}

// JoinArena is the resolver for the joinArena field.
func (r *mutationResolver) JoinArena(ctx context.Context, input model.JoinArenaInput) (*model.JoinArenaPayload, error) {
	panic(fmt.Errorf("not implemented: JoinArena - joinArena"))
}

// LeaveArena is the resolver for the leaveArena field.
func (r *mutationResolver) LeaveArena(ctx context.Context, input model.LeaveArenaInput) (*model.LeaveArenaPayload, error) {
	panic(fmt.Errorf("not implemented: LeaveArena - leaveArena"))
}

// SubmitAction is the resolver for the submitAction field.
func (r *mutationResolver) SubmitAction(ctx context.Context, input model.SubmitActionInput) (*model.SubmitActionPayload, error) {
	panic(fmt.Errorf("not implemented: SubmitAction - submitAction"))
}

// SetArenaConfig is the resolver for the setArenaConfig field.
func (r *mutationResolver) SetArenaConfig(ctx context.Context, input model.SetArenaConfigInput) (*model.SetArenaConfigPayload, error) {
	panic(fmt.Errorf("not implemented: SetArenaConfig - setArenaConfig"))
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*model.Health, error) {
	panic(fmt.Errorf("not implemented: Health - health"))
}

// Arena is the resolver for the arena field.
func (r *queryResolver) Arena(ctx context.Context, id uuid.UUID) (*model.Arena, error) {
	panic(fmt.Errorf("not implemented: Arena - arena"))
}

// Arenas is the resolver for the arenas field.
func (r *queryResolver) Arenas(ctx context.Context, filter *model.ArenaFilter, page *model.PageInput) (*model.ArenaPage, error) {
	panic(fmt.Errorf("not implemented: Arenas - arenas"))
}

// ArenaSnapshot is the resolver for the arenaSnapshot field.
func (r *queryResolver) ArenaSnapshot(ctx context.Context, arenaID uuid.UUID, atTick int64) (*model.ArenaSnapshot, error) {
	panic(fmt.Errorf("not implemented: ArenaSnapshot - arenaSnapshot"))
}

// ArenaHistory is the resolver for the arenaHistory field.
func (r *queryResolver) ArenaHistory(ctx context.Context, arenaID uuid.UUID, fromTick int64, toTick int64, mode *model.DiffMode) ([]*model.ArenaSnapshot, error) {
	panic(fmt.Errorf("not implemented: ArenaHistory - arenaHistory"))
}

// Leaderboard is the resolver for the leaderboard field.
func (r *queryResolver) Leaderboard(ctx context.Context, arenaID uuid.UUID, top *int32) ([]*model.LeaderboardEntry, error) {
	panic(fmt.Errorf("not implemented: Leaderboard - leaderboard"))
}

// Metrics is the resolver for the metrics field.
func (r *queryResolver) Metrics(ctx context.Context, arenaID uuid.UUID, windowSeconds *int32) (*model.ArenaMetrics, error) {
	panic(fmt.Errorf("not implemented: Metrics - metrics"))
}

// Organism is the resolver for the organism field.
func (r *queryResolver) Organism(ctx context.Context, id uuid.UUID) (*model.Organism, error) {
	panic(fmt.Errorf("not implemented: Organism - organism"))
}

// Genome is the resolver for the genome field.
func (r *queryResolver) Genome(ctx context.Context, id uuid.UUID) (*model.Genome, error) {
	panic(fmt.Errorf("not implemented: Genome - genome"))
}

// ArenaEvents is the resolver for the arenaEvents field.
func (r *subscriptionResolver) ArenaEvents(ctx context.Context, arenaID uuid.UUID) (<-chan model.ArenaEvent, error) {
	panic(fmt.Errorf("not implemented: ArenaEvents - arenaEvents"))
}

// ArenaSnapshots is the resolver for the arenaSnapshots field.
func (r *subscriptionResolver) ArenaSnapshots(ctx context.Context, arenaID uuid.UUID, mode *model.DiffMode) (<-chan *model.ArenaSnapshot, error) {
	panic(fmt.Errorf("not implemented: ArenaSnapshots - arenaSnapshots"))
}

// ArenaMetrics is the resolver for the arenaMetrics field.
func (r *subscriptionResolver) ArenaMetrics(ctx context.Context, arenaID uuid.UUID, windowSeconds *int32) (<-chan *model.ArenaMetrics, error) {
	panic(fmt.Errorf("not implemented: ArenaMetrics - arenaMetrics"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
