// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

type ActionPayload interface {
	IsActionPayload()
}

type ArenaEvent interface {
	IsArenaEvent()
}

type ActionAcceptedEvent struct {
	ArenaID  uuid.UUID     `json:"arenaId"`
	At       time.Time     `json:"at"`
	ActionID uuid.UUID     `json:"actionId"`
	Action   *PlayerAction `json:"action"`
}

func (ActionAcceptedEvent) IsArenaEvent() {}

type ActionRejectedEvent struct {
	ArenaID  uuid.UUID `json:"arenaId"`
	At       time.Time `json:"at"`
	ActionID uuid.UUID `json:"actionId"`
	Reason   string    `json:"reason"`
}

func (ActionRejectedEvent) IsArenaEvent() {}

type AddNutrientsInput struct {
	Area   *AreaInput `json:"area"`
	Amount int32      `json:"amount"`
}

type AddNutrientsPayload struct {
	Area   *Area `json:"area"`
	Amount int32 `json:"amount"`
}

func (AddNutrientsPayload) IsActionPayload() {}

type Area struct {
	X      int32 `json:"x"`
	Y      int32 `json:"y"`
	Width  int32 `json:"width"`
	Height int32 `json:"height"`
}

type AreaInput struct {
	X      int32 `json:"x"`
	Y      int32 `json:"y"`
	Width  int32 `json:"width"`
	Height int32 `json:"height"`
}

type Arena struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Status       ArenaStatus    `json:"status"`
	CreatedAt    time.Time      `json:"createdAt"`
	StartedAt    *time.Time     `json:"startedAt,omitempty"`
	FinishedAt   *time.Time     `json:"finishedAt,omitempty"`
	Tick         int64          `json:"tick"`
	Config       *ArenaConfig   `json:"config"`
	Players      []*Player      `json:"players"`
	World        *WorldInfo     `json:"world"`
	LastSnapshot *ArenaSnapshot `json:"lastSnapshot,omitempty"`
}

type ArenaConfig struct {
	TickMillis         int32        `json:"tickMillis"`
	Width              int32        `json:"width"`
	Height             int32        `json:"height"`
	DiffusionRate      float64      `json:"diffusionRate"`
	MutationRate       float64      `json:"mutationRate"`
	MaxOrganisms       int32        `json:"maxOrganisms"`
	SnapshotEveryTicks int32        `json:"snapshotEveryTicks"`
	Temperature        *Temperature `json:"temperature"`
}

type ArenaConfigInput struct {
	TickMillis         int32             `json:"tickMillis"`
	Width              int32             `json:"width"`
	Height             int32             `json:"height"`
	DiffusionRate      float64           `json:"diffusionRate"`
	MutationRate       float64           `json:"mutationRate"`
	MaxOrganisms       int32             `json:"maxOrganisms"`
	SnapshotEveryTicks int32             `json:"snapshotEveryTicks"`
	Temperature        *TemperatureInput `json:"temperature"`
}

type ArenaFilter struct {
	Status       *ArenaStatus `json:"status,omitempty"`
	NameContains *string      `json:"nameContains,omitempty"`
}

type ArenaLifecycleEvent struct {
	ArenaID    uuid.UUID               `json:"arenaId"`
	At         time.Time               `json:"at"`
	Kind       ArenaLifecycleEventKind `json:"kind"`
	ByPlayerID *uuid.UUID              `json:"byPlayerId,omitempty"`
}

func (ArenaLifecycleEvent) IsArenaEvent() {}

type ArenaMetrics struct {
	ArenaID              uuid.UUID     `json:"arenaId"`
	WindowSeconds        int32         `json:"windowSeconds"`
	At                   time.Time     `json:"at"`
	Tick                 int64         `json:"tick"`
	OrganismCount        int32         `json:"organismCount"`
	BirthsPerSec         float64       `json:"birthsPerSec"`
	DeathsPerSec         float64       `json:"deathsPerSec"`
	MutationRateObserved float64       `json:"mutationRateObserved"`
	TopGenomes           []*GenomeStat `json:"topGenomes"`
}

type ArenaPage struct {
	Items  []*Arena `json:"items"`
	Total  int32    `json:"total"`
	Limit  int32    `json:"limit"`
	Offset int32    `json:"offset"`
}

type ArenaSnapshot struct {
	ArenaID    uuid.UUID     `json:"arenaId"`
	Tick       int64         `json:"tick"`
	CapturedAt time.Time     `json:"capturedAt"`
	Mode       DiffMode      `json:"mode"`
	Grid       *GridSnapshot `json:"grid,omitempty"`
	Delta      *GridDelta    `json:"delta,omitempty"`
	Stats      *TickStats    `json:"stats"`
}

type CellPatch struct {
	X     int32 `json:"x"`
	Y     int32 `json:"y"`
	Value int32 `json:"value"`
}

type CreateArenaInput struct {
	Name   string            `json:"name"`
	Config *ArenaConfigInput `json:"config"`
}

type CreateArenaPayload struct {
	Arena *Arena `json:"arena"`
}

type DropAntibioticInput struct {
	Area          *AreaInput     `json:"area"`
	Kind          AntibioticKind `json:"kind"`
	Concentration float64        `json:"concentration"`
}

type DropAntibioticPayload struct {
	Area          *Area          `json:"area"`
	Kind          AntibioticKind `json:"kind"`
	Concentration float64        `json:"concentration"`
}

func (DropAntibioticPayload) IsActionPayload() {}

type Gene struct {
	Name        string  `json:"name"`
	Value       float64 `json:"value"`
	Description *string `json:"description,omitempty"`
}

type Genome struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	Genes     []*Gene   `json:"genes"`
	Signature string    `json:"signature"`
}

type GenomeStat struct {
	GenomeID   uuid.UUID `json:"genomeId"`
	Signature  string    `json:"signature"`
	Count      int32     `json:"count"`
	AvgFitness *float64  `json:"avgFitness,omitempty"`
}

type GridDelta struct {
	Width              int32        `json:"width"`
	Height             int32        `json:"height"`
	OrganismPatches    []*CellPatch `json:"organismPatches"`
	NutrientPatches    []*CellPatch `json:"nutrientPatches"`
	AntibioticPatches  []*CellPatch `json:"antibioticPatches"`
	TemperaturePatches []*CellPatch `json:"temperaturePatches"`
	Encoding           string       `json:"encoding"`
}

type GridSnapshot struct {
	Width       int32  `json:"width"`
	Height      int32  `json:"height"`
	Organisms   string `json:"organisms"`
	Nutrients   string `json:"nutrients"`
	Antibiotic  string `json:"antibiotic"`
	Temperature string `json:"temperature"`
	Encoding    string `json:"encoding"`
}

type Health struct {
	Ok      bool      `json:"ok"`
	Version string    `json:"version"`
	Now     time.Time `json:"now"`
}

type JoinArenaInput struct {
	ArenaID     uuid.UUID `json:"arenaId"`
	DisplayName string    `json:"displayName"`
}

type JoinArenaPayload struct {
	Player       *Player `json:"player"`
	SessionToken string  `json:"sessionToken"`
}

type LeaderboardEntry struct {
	Rank            int32        `json:"rank"`
	OrganismID      uuid.UUID    `json:"organismId"`
	Fitness         float64      `json:"fitness"`
	Kind            OrganismKind `json:"kind"`
	GenomeSignature string       `json:"genomeSignature"`
}

type LeaveArenaInput struct {
	ArenaID  uuid.UUID `json:"arenaId"`
	PlayerID uuid.UUID `json:"playerId"`
}

type LeaveArenaPayload struct {
	Ok bool `json:"ok"`
}

type Lineage struct {
	OrganismID uuid.UUID   `json:"organismId"`
	ParentID   *uuid.UUID  `json:"parentId,omitempty"`
	Generation int32       `json:"generation"`
	Mutations  []*Mutation `json:"mutations"`
}

type Mutation struct {
}

type Organism struct {
	ID        uuid.UUID    `json:"id"`
	Kind      OrganismKind `json:"kind"`
	CreatedAt time.Time    `json:"createdAt"`
	ArenaID   uuid.UUID    `json:"arenaId"`
	Position  *Point       `json:"position"`
	Energy    float64      `json:"energy"`
	Fitness   float64      `json:"fitness"`
	Genome    *Genome      `json:"genome"`
	Lineage   *Lineage     `json:"lineage"`
}

type PageInput struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type PauseArenaInput struct {
	ArenaID uuid.UUID `json:"arenaId"`
}

type PauseArenaPayload struct {
	Ok    bool   `json:"ok"`
	Arena *Arena `json:"arena"`
}

type Player struct {
	ID          uuid.UUID  `json:"id"`
	DisplayName string     `json:"displayName"`
	JoinedAt    time.Time  `json:"joinedAt"`
	Role        PlayerType `json:"role"`
}

type PlayerAction struct {
	ID          uuid.UUID     `json:"id"`
	Type        ActionType    `json:"type"`
	ArenaID     uuid.UUID     `json:"arenaId"`
	PlayerID    uuid.UUID     `json:"playerId"`
	SubmittedAt time.Time     `json:"submittedAt"`
	ApplyAtTick int64         `json:"applyAtTick"`
	Payload     ActionPayload `json:"payload"`
}

type Point struct {
	X int32 `json:"x"`
	Y int32 `json:"y"`
}

type PointInput struct {
	X int32 `json:"x"`
	Y int32 `json:"y"`
}

type Query struct {
}

type ResumeArenaInput struct {
	ArenaID uuid.UUID `json:"arenaId"`
}

type ResumeArenaPayload struct {
	Ok    bool   `json:"ok"`
	Arena *Arena `json:"arena"`
}

type SetArenaConfigInput struct {
	ArenaID uuid.UUID         `json:"arenaId"`
	Config  *ArenaConfigInput `json:"config"`
}

type SetArenaConfigPayload struct {
	Ok    bool   `json:"ok"`
	Arena *Arena `json:"arena"`
}

type SetTemperatureInput struct {
	Temperature *TemperatureInput `json:"temperature"`
}

type SetTemperaturePayload struct {
	Temperature *Temperature `json:"temperature"`
}

func (SetTemperaturePayload) IsActionPayload() {}

type SnapshotEmittedEvent struct {
	ArenaID uuid.UUID `json:"arenaId"`
	At      time.Time `json:"at"`
	Tick    int64     `json:"tick"`
	Mode    DiffMode  `json:"mode"`
}

func (SnapshotEmittedEvent) IsArenaEvent() {}

type SpawnOrganismInput struct {
	Kind             OrganismKind `json:"kind"`
	Position         *PointInput  `json:"position"`
	GenomeTemplateID *uuid.UUID   `json:"genomeTemplateId,omitempty"`
}

type SpawnOrganismPayload struct {
	Kind             OrganismKind `json:"kind"`
	Position         *Point       `json:"position"`
	GenomeTemplateID *uuid.UUID   `json:"genomeTemplateId,omitempty"`
}

func (SpawnOrganismPayload) IsActionPayload() {}

type StartArenaInput struct {
	ArenaID uuid.UUID `json:"arenaId"`
}

type StartArenaPayload struct {
	Ok    bool   `json:"ok"`
	Arena *Arena `json:"arena"`
}

type StopArenaInput struct {
	ArenaID uuid.UUID `json:"arenaId"`
}

type StopArenaPayload struct {
	Ok    bool   `json:"ok"`
	Arena *Arena `json:"arena"`
}

type SubmitActionInput struct {
	ArenaID        uuid.UUID            `json:"arenaId"`
	PlayerID       uuid.UUID            `json:"playerId"`
	Type           ActionType           `json:"type"`
	ApplyAtTick    *int64               `json:"applyAtTick,omitempty"`
	AddNutrients   *AddNutrientsInput   `json:"addNutrients,omitempty"`
	DropAntibiotic *DropAntibioticInput `json:"dropAntibiotic,omitempty"`
	SetTemperature *SetTemperatureInput `json:"setTemperature,omitempty"`
	SpawnOrganism  *SpawnOrganismInput  `json:"spawnOrganism,omitempty"`
}

type SubmitActionPayload struct {
	ActionID        uuid.UUID `json:"actionId"`
	Accepted        bool      `json:"accepted"`
	Reason          *string   `json:"reason,omitempty"`
	WillApplyAtTick int64     `json:"willApplyAtTick"`
}

type Subscription struct {
}

type Temperature struct {
	Value float64         `json:"value"`
	Unit  TemperatureUnit `json:"unit"`
}

type TemperatureInput struct {
	Value float64         `json:"value"`
	Unit  TemperatureUnit `json:"unit"`
}

type TickAdvancedEvent struct {
	ArenaID uuid.UUID `json:"arenaId"`
	At      time.Time `json:"at"`
	Tick    int64     `json:"tick"`
}

func (TickAdvancedEvent) IsArenaEvent() {}

type TickStats struct {
	OrganismCount int32    `json:"organismCount"`
	Births        int32    `json:"births"`
	Deaths        int32    `json:"deaths"`
	Mutations     int32    `json:"mutations"`
	AvgFitness    *float64 `json:"avgFitness,omitempty"`
}

type WorldInfo struct {
	Width  int32        `json:"width"`
	Height int32        `json:"height"`
	Layers []WorldLayer `json:"layers"`
}

type ActionType string

const (
	ActionTypeAddNutrients   ActionType = "ADD_NUTRIENTS"
	ActionTypeDropAntibiotic ActionType = "DROP_ANTIBIOTIC"
	ActionTypeSetTemperature ActionType = "SET_TEMPERATURE"
	ActionTypeSpawnOrganism  ActionType = "SPAWN_ORGANISM"
)

var AllActionType = []ActionType{
	ActionTypeAddNutrients,
	ActionTypeDropAntibiotic,
	ActionTypeSetTemperature,
	ActionTypeSpawnOrganism,
}

func (e ActionType) IsValid() bool {
	switch e {
	case ActionTypeAddNutrients, ActionTypeDropAntibiotic, ActionTypeSetTemperature, ActionTypeSpawnOrganism:
		return true
	}
	return false
}

func (e ActionType) String() string {
	return string(e)
}

func (e *ActionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ActionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ActionType", str)
	}
	return nil
}

func (e ActionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ActionType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ActionType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AntibioticKind string

const (
	AntibioticKindA AntibioticKind = "A"
	AntibioticKindB AntibioticKind = "B"
	AntibioticKindC AntibioticKind = "C"
)

var AllAntibioticKind = []AntibioticKind{
	AntibioticKindA,
	AntibioticKindB,
	AntibioticKindC,
}

func (e AntibioticKind) IsValid() bool {
	switch e {
	case AntibioticKindA, AntibioticKindB, AntibioticKindC:
		return true
	}
	return false
}

func (e AntibioticKind) String() string {
	return string(e)
}

func (e *AntibioticKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AntibioticKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AntibioticKind", str)
	}
	return nil
}

func (e AntibioticKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AntibioticKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AntibioticKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ArenaLifecycleEventKind string

const (
	ArenaLifecycleEventKindCreated  ArenaLifecycleEventKind = "CREATED"
	ArenaLifecycleEventKindStarted  ArenaLifecycleEventKind = "STARTED"
	ArenaLifecycleEventKindPaused   ArenaLifecycleEventKind = "PAUSED"
	ArenaLifecycleEventKindResumed  ArenaLifecycleEventKind = "RESUMED"
	ArenaLifecycleEventKindStopped  ArenaLifecycleEventKind = "STOPPED"
	ArenaLifecycleEventKindFinished ArenaLifecycleEventKind = "FINISHED"
)

var AllArenaLifecycleEventKind = []ArenaLifecycleEventKind{
	ArenaLifecycleEventKindCreated,
	ArenaLifecycleEventKindStarted,
	ArenaLifecycleEventKindPaused,
	ArenaLifecycleEventKindResumed,
	ArenaLifecycleEventKindStopped,
	ArenaLifecycleEventKindFinished,
}

func (e ArenaLifecycleEventKind) IsValid() bool {
	switch e {
	case ArenaLifecycleEventKindCreated, ArenaLifecycleEventKindStarted, ArenaLifecycleEventKindPaused, ArenaLifecycleEventKindResumed, ArenaLifecycleEventKindStopped, ArenaLifecycleEventKindFinished:
		return true
	}
	return false
}

func (e ArenaLifecycleEventKind) String() string {
	return string(e)
}

func (e *ArenaLifecycleEventKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ArenaLifecycleEventKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ArenaLifecycleEventKind", str)
	}
	return nil
}

func (e ArenaLifecycleEventKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ArenaLifecycleEventKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ArenaLifecycleEventKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ArenaStatus string

const (
	ArenaStatusPending  ArenaStatus = "PENDING"
	ArenaStatusRunning  ArenaStatus = "RUNNING"
	ArenaStatusPaused   ArenaStatus = "PAUSED"
	ArenaStatusFinished ArenaStatus = "FINISHED"
)

var AllArenaStatus = []ArenaStatus{
	ArenaStatusPending,
	ArenaStatusRunning,
	ArenaStatusPaused,
	ArenaStatusFinished,
}

func (e ArenaStatus) IsValid() bool {
	switch e {
	case ArenaStatusPending, ArenaStatusRunning, ArenaStatusPaused, ArenaStatusFinished:
		return true
	}
	return false
}

func (e ArenaStatus) String() string {
	return string(e)
}

func (e *ArenaStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ArenaStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ArenaStatus", str)
	}
	return nil
}

func (e ArenaStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ArenaStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ArenaStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DiffMode string

const (
	DiffModeFull  DiffMode = "FULL"
	DiffModeDelta DiffMode = "DELTA"
)

var AllDiffMode = []DiffMode{
	DiffModeFull,
	DiffModeDelta,
}

func (e DiffMode) IsValid() bool {
	switch e {
	case DiffModeFull, DiffModeDelta:
		return true
	}
	return false
}

func (e DiffMode) String() string {
	return string(e)
}

func (e *DiffMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DiffMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DiffMode", str)
	}
	return nil
}

func (e DiffMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DiffMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DiffMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MutationKind string

const (
	MutationKindSnp         MutationKind = "SNP"
	MutationKindInsertion   MutationKind = "INSERTION"
	MutationKindDeletion    MutationKind = "DELETION"
	MutationKindDuplication MutationKind = "DUPLICATION"
)

var AllMutationKind = []MutationKind{
	MutationKindSnp,
	MutationKindInsertion,
	MutationKindDeletion,
	MutationKindDuplication,
}

func (e MutationKind) IsValid() bool {
	switch e {
	case MutationKindSnp, MutationKindInsertion, MutationKindDeletion, MutationKindDuplication:
		return true
	}
	return false
}

func (e MutationKind) String() string {
	return string(e)
}

func (e *MutationKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MutationKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MutationKind", str)
	}
	return nil
}

func (e MutationKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MutationKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MutationKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OrganismKind string

const (
	OrganismKindBacteria OrganismKind = "BACTERIA"
	OrganismKindFungi    OrganismKind = "FUNGI"
	OrganismKindPhage    OrganismKind = "PHAGE"
)

var AllOrganismKind = []OrganismKind{
	OrganismKindBacteria,
	OrganismKindFungi,
	OrganismKindPhage,
}

func (e OrganismKind) IsValid() bool {
	switch e {
	case OrganismKindBacteria, OrganismKindFungi, OrganismKindPhage:
		return true
	}
	return false
}

func (e OrganismKind) String() string {
	return string(e)
}

func (e *OrganismKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrganismKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrganismKind", str)
	}
	return nil
}

func (e OrganismKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrganismKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrganismKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PlayerType string

const (
	PlayerTypeAdmin  PlayerType = "ADMIN"
	PlayerTypePlayer PlayerType = "PLAYER"
)

var AllPlayerType = []PlayerType{
	PlayerTypeAdmin,
	PlayerTypePlayer,
}

func (e PlayerType) IsValid() bool {
	switch e {
	case PlayerTypeAdmin, PlayerTypePlayer:
		return true
	}
	return false
}

func (e PlayerType) String() string {
	return string(e)
}

func (e *PlayerType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PlayerType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PlayerType", str)
	}
	return nil
}

func (e PlayerType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PlayerType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PlayerType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TemperatureUnit string

const (
	TemperatureUnitC TemperatureUnit = "C"
)

var AllTemperatureUnit = []TemperatureUnit{
	TemperatureUnitC,
}

func (e TemperatureUnit) IsValid() bool {
	switch e {
	case TemperatureUnitC:
		return true
	}
	return false
}

func (e TemperatureUnit) String() string {
	return string(e)
}

func (e *TemperatureUnit) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TemperatureUnit(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TemperatureUnit", str)
	}
	return nil
}

func (e TemperatureUnit) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TemperatureUnit) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TemperatureUnit) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorldLayer string

const (
	WorldLayerOrganisms   WorldLayer = "ORGANISMS"
	WorldLayerNutrients   WorldLayer = "NUTRIENTS"
	WorldLayerAntibiotic  WorldLayer = "ANTIBIOTIC"
	WorldLayerTemperature WorldLayer = "TEMPERATURE"
)

var AllWorldLayer = []WorldLayer{
	WorldLayerOrganisms,
	WorldLayerNutrients,
	WorldLayerAntibiotic,
	WorldLayerTemperature,
}

func (e WorldLayer) IsValid() bool {
	switch e {
	case WorldLayerOrganisms, WorldLayerNutrients, WorldLayerAntibiotic, WorldLayerTemperature:
		return true
	}
	return false
}

func (e WorldLayer) String() string {
	return string(e)
}

func (e *WorldLayer) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorldLayer(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorldLayer", str)
	}
	return nil
}

func (e WorldLayer) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorldLayer) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorldLayer) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
